# Generated by Django 4.2.5 on 2023-09-28 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConteudo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtitulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='curso_imagens/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('itens_conteudo', models.ManyToManyField(blank=True, to='core.itemconteudo')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez_logado', models.DateTimeField(blank=True, null=True)),
                ('tempo_logado', models.DurationField(blank=True, null=True)),
                ('cursos_liberados', models.ManyToManyField(blank=True, to='core.curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
